### ISSUE TITLE
can we add build files to the released package for simpler browser testing?

### ISSUE THREAD

**Issue by gr2m** [nolanlawson/pouchdb-memory#1]
I’m happy to set this up with a build script and semantic-release, so that it builds automatically before releasing, and am happy to help maintain this package to keep the version in sync with PouchDB version, as the build version would need to be rebuild each time

**Comment by gr2m** [comment]
actually, nevermind, maybe it’s a better idea to have a build step in my test setup, probably much less overhead

**Comment by nolanlawson** [comment]
Yeah that's kind of where I was going with this package. Keep it as simple as possible! Doesn't even need any tests (imo).
